"files" : [
  {
    "source" : "/docs/zh/**/*.md",
    "translation" : "/docs/%two_letters_code%/**/%original_file_name%",
    "languages_mapping" : {
      "two_letters_code" : {
        "en" : "",
        "zh": "zh"
      }
    }
  }
]
