"project_identifier": "vite-wiki"
"api_key_env": "CROWDIN_API_KEY"
"base_path": "."
"files" : [
  {
    "source" : "/docs/*/**/*.md",
    "translation" : "/docs/%two_letters_code%/**/%original_file_name%",
    "languages_mapping" : {
      "two_letters_code" : {
        "en" : "",
        "zh": "zh"
      }
    },
    "ignore" : [
      "/docs/%two_letters_code%/**/%original_file_name%", #ignore the translated files
    ]
  }
]
